### PR TITLE
feat: add missing editor icons

### LINKED ISSUE #1229: Update/create icons for the substation plugin
**Is your feature request related to a problem? Please describe.**
As a user of OpenSCD, particularly of the Substation plugin, I want to have a clear way to differentiate in the screen at the root level which elements are Substations and which are Lines or Processes.

**Describe the solution you'd like**
I would like to see the elements `Substation`, `Line` and `Process` to appear in the Substation plugin with an icon similar to the one that for example the `PowerTransformer` elements have:

image

**Acceptance criteria**
- Add icons for the aforementioned elements in the Substation plugin
- - Find suitable icons agreed by the community for the three elements 
- Show the new Icons:
Substation icon: https://www.flaticon.com/free-icon/electric-factory_4882901?term=substation&page=1&position=2&origin=search&related_id=4882901
Line: https://www.flaticon.com/free-icon/power-line_125390
Process: https://www.flaticon.com/free-icon/process_2041633?term=process&page=1&position=25&origin=style&related_id=2041633
Comply with icon license critria

Background:
Technical approach: Copy paste the SVG of the linked icon in this issue and put it in the package/open-scd/src/icons/icons.ts folder.

### PR DESCRIPTION
**Pull request by Stef3st**
closes #1229

### CODE REVIEW

**Comment by Stef3st** [comment]
As discussed, this PR contains adding icons to the following substation plugin editors:
- Line
- Process
- Substation
- Transformer winding
- Bay
- Voltage level

**Comment by Stef3st** [comment]
Thanks for your review @pascalwilbrink!

I agree, the styles variable should take care of the styling. I added a CSS class to the styles and made these icons part of that class. I also included the other editors in for the substation plugin that had this inline styling.

**Review by pascalwilbrink — APPROVED** [review]
lgtm

**Comment by Sander3003** [comment]
Is this feature already released on openscd.github.io?

**Comment by juancho0202** [comment]
@Sander3003 currently the workflow for releasing to [openscd.github.io](openscd.github.io) is broken, I attempted a fix last week but it missed one detail, I already identified the missing bit and successfully deployed with the same workflow in my personal fork of openscd ([juancho0202.github.io](juancho0202@github.io)). I will talk to @trusz today about it and see if we can merge the new fix.

**Pull request merged**
