### PR TITLE
Add complex actions

### LINKED ISSUE #98: Add complex actions
The log easily gets flooded with many individually un- and redoable entries when a single user action causes many simple editor actions (`Create`, `Update`, `Move`, or `Delete`) to happen at once.

A complex editor action type which consists in an array of simple editor actions that are handled and committed to the log as a single un- and redoable entry is intended to help alleviate this issue.

### PR DESCRIPTION
**Pull request by c-dinkel**
Resolves #98 .

### CODE REVIEW

**Comment by c-dinkel** [comment]
The code in this draft is currently not exercised at all and needs unit tests before merging. I will refactor and write tests as soon as @JakobVogelsang agrees to the proposed API for `ComplexAction`s.

**Review by JakobVogelsang — COMMENTED** [review]
I like the API. I think it fits our need. The only thing we might consider is a flexible title for complex actions. Ideally you can decide for each service individually.

**Review by JakobVogelsang — APPROVED** [review]
LGTM

**Review by JakobVogelsang — APPROVED** [review]
LGTM

**Pull request merged**
