### PR TITLE
fix: reduce items on menu if elsewhere in the UI

### LINKED ISSUE #1241: Reduce items on menu if available elsewhere in the UI
**Is your feature request related to a problem? Please describe.**

As a user of OpenSCD, I'd like the menu to be simple and not repeat functionality used elsewhere (and rarely used from the menu).

(splitting apart of #1225)

**Describe the solution you'd like**

I want to suggest that we could declutter the top of the menu in OpenSCD by:

* removing undo and redo and relying on the top right of the app
* removing view log and view diagnostics menu items and instead relying on the top right of the app where we have buttons for these

### PR DESCRIPTION
**Pull request by Stef3st**
closes #1241

### CODE REVIEW

**Review by danyill — CHANGES_REQUESTED** [review]
Thank you for attending to this :+1: 

However  I can't open the "Import IEDs", "Settings" or "Extensions" menu items with this PR when I did some local testing so I think perhaps other modifications are required elsewhere otherwise the menu is not in synch with some other data source?

**Comment by Stef3st** [comment]
> Thank you for attending to this 👍
> 
> However I can't open the "Import IEDs", "Settings" or "Extensions" menu items with this PR when I did some local testing so I think perhaps other modifications are required elsewhere otherwise the menu is not in synch with some other data source?

Thank you for checking it out, I'll look at it and let you know when Ive got a solution for this!

**Comment by Stef3st** [comment]
@danyill fixed the problem. It still tried to render menu items that weren't created any more. Should work fine now!

**Review by danyill — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
