### PR TITLE
feat(wizards/reportcontrol): allow basic ReportControl manipulation capability

### LINKED ISSUE #506: Incorrect rendering of FCDA elements in DataSet
There is a difference when rendering a DataSet located in a LN0 and one located in LN. The first shows the path from logical node to the data the second shows the logical device name. My guess is that the identity string differs for the two.

### PR DESCRIPTION
**Pull request by JakobVogelsang**
Also closes #506 #475

### CODE REVIEW

**Comment by JakobVogelsang** [comment]
@danyill @Sander3003 @randy993 we have added something we call dynamic sub-wizards. This allows you to navigate more fluently between wizards that were open within other wizards. You can test it here with the ReportControl wizards that we will add very soon. What do you think about this UI?

**Review by dlabordus — APPROVED** [review]

**Comment by Sander3003** [comment]
The reporting block shows the wrong tooltip (GOOSE instead of Reporting):
image

**Comment by JakobVogelsang** [comment]
Shoot :( I will change that.

**Comment by Sander3003** [comment]
image
We would suggest to change the edit button into a "ok" button.

**Comment by Sander3003** [comment]
The UI goods look to me!

**Comment by JakobVogelsang** [comment]
How about `save` as in the edit wizard for the control block itself?

**Comment by Sander3003** [comment]
Save could work as well as.

**Comment by JakobVogelsang** [comment]
> Save could work as well as.

I will put it this PR #507  as this wizard is commonly used.

**Pull request merged**
