### PR TITLE
refactor(editors/template): move EnumType from web-components to wizards

### LINKED ISSUE #220: Refactor `EnumType` web-component
`EnumType` lists are a list of enumtype web-components. This implementation is different to the implementation for `LNodeType`, `DOType` and `DAType` lists and need to changed to fit the other compenents.

### PR DESCRIPTION
**Pull request by JakobVogelsang**
Closes #220

### CODE REVIEW

**Review by c-dinkel — APPROVED** [review]
Looks great 😁👍 ! Do we still need subwizard in foundation?

**Comment by JakobVogelsang** [comment]
I will check. Would it be ok for you, if we remove this with a separate pull request?

**Review by c-dinkel — APPROVED** [review]
LGTM, thanks for the great refactor!

**Comment by c-dinkel** [comment]
> I will check. Would it be ok for you, if we remove this with a separate pull request?

Absolutely, we can do that and merge this as soon as the tests are green.

**Pull request merged**
