### PR TITLE
chore: fix husky, lint and format code

### PR DESCRIPTION
**Pull request by ca-d**
This fixes the husky installation to run pre-commit and commit-msg hooks again. This has not been working for a long time. Committing this also required fixing all linter errors, such that our code now actually lints again, and allowed me to finally run the formatter for the first time in ages, meaning we have linted and nicely formatted code again! :tada:

### CODE REVIEW

**Comment by ca-d** [comment]
Converted this to draft until https://github.com/openscd/open-scd/pull/1285 is merged, since this sits on top of that.

**Comment by samirromdhani** [comment]
Hi, I started doing as such fixes last month in my fork, here is the [commit](https://github.com/samirromdhani/open-scd/commit/2a22c8423c8e2761d74987b0ab2ee01c4a7015f2) (still wip). I recommand using [realworld](https://github.com/gothinkster/realworld) project as it comes with many well-specified configuration.

**Comment by ca-d** [comment]
> Hi, I started doing as such fixes last month in my fork

Thanks for considering this issue! I'm not sure I understand quite what you mean. Does your commit actually fix the `husky` pre-commit hook package? That is the topic of this pull request.

Your commit looks to me like it just includes a different eslint and prettier configuration, without actually fixing husky. If I'm not mistaken about that, be advised that this project already has a linter and formatter configuration, which follows the `open-wc` recommendation that this project was generated with.

**Comment by trusz** [comment]
This PR has a lot of conflicts but I'd like to keep it around because we can cherry-pick the fixes.

**Comment by trusz** [comment]
because of the re-structuring this PR has too many conflicts. I will close it for now and add the feature maybe later.

**Pull request closed without merging**
