### PR TITLE
feat(editor/publisher): add IED filter button

### PR DESCRIPTION
**Pull request by JakobVogelsang**
Pure prototype for a nerdy Friday :)

### CODE REVIEW

**Comment by JakobVogelsang** [comment]
@danyill what you think of the filter button in the GSEControl list next to the search text fiels?

**Comment by danyill** [comment]
I quite like it, as a prototype I guess we'd need to do a little work on the UI. This could be a powerful way to interact with large files.

Part of me says, though that if I'm filtering e.g. GSEControl and the IED name is in the secondary text then a single flat filter should be able to pick that up too and that IEDs with non-matching GSEControls simply shouldn't appear.

It may be a UI crime however to provide a parent/child and then "munge" them together within the filter bar and sooner or later I can see there will be too many fields/options and the user experience will suffer.

But maybe with the parent being the IED and the child being say the GSEControl name, then it might be OK to filter on IED name and GSE control name within a single filter bar?

:grey_question: 

This is somewhat similar to: https://github.com/openscd/open-scd/issues/655 and #560 

However, having a filter is probably a more "future-proof solution". I know it's only a prototype but I'd consider putting the filter icon on the right and having a pop-out for the IEDs name - putting at the top and displacing the existing list is a little confusing.

**Comment by JakobVogelsang** [comment]
@danyill I have made some more CSS. I think this is coming close to the recommendations. I also made `noninteractive` elements in the filtered list filterable. Now you have both the solutions combined. I would love to get your opinion.

**Comment by danyill** [comment]
Thank you for looking at this feedback. I like it! With an "IED name" heading in the filter I think we'd almost be there but there are some performance issues in large files:

* The fact that it is reactive on the list as each item selection is made, makes the user interface "sticky" with a large scd file.
(I contemplate whether we need service workers indexing things in the background if want this kind of reactive interface).
*  I wonder if the filter should default to enabling everything. Better performance would be to enable nothing and mean that the user didn't first have to "deselect all".
* Hitting "deselect all" or "select all" in the filter is _very_ sticky in a large scd file. I wonder if it is running multiple updates or whether this is just the penalty of a large file.
* I think it would be OK in the filter that the reactive update didn't occur until the panel was X-ed. That would dramatically improve performance.
* I wonder if the filter should be capped to 100% of vh and scrollable without scrolling the "outer pane", so the filter only occupies one screen height.

**Pull request closed without merging**
