### PR TITLE
Refactor project creation

### LINKED ISSUE #94: OpenSCD does not condsider existing file extentions
When project name is `NewProject.scd` the editor does add another `*.scd`.

### LINKED ISSUE #95: Creating a new project does not reset the editor log.
Clicking "New project" in the menu should also remove all hitherto existing entries from the log.

### PR DESCRIPTION
**Pull request by c-dinkel**
Resolves #94 .
Resolves #95 .

### CODE REVIEW

**Comment by c-dinkel** [comment]
This is finally ready to review. The "New Project" dialog currently doesn't seem to need to be a wizard. @JakobVogelsang do you think it would be worth turning it into a regular dialog?

**Comment by JakobVogelsang** [comment]
I would prefer this.

**Review by JakobVogelsang — APPROVED** [review]
LGTM

**Comment by c-dinkel** [comment]
> I would prefer this on a long run. But would like to do those minor issues later. What do you think?

I agree, this is not urgent.

**Pull request merged**
