### PR TITLE
Update snapshots

### LINKED ISSUE #676: Regenerate Snapshots from Tests
As a developer
I would like to know how to manage Snapshots
So it does not get messy

Acceptance:
What/why/when explained, including:
How do we work with snapshots
General behavior for approving snapshots in PR's

Background (old)
Maybe it's a idea to regenerate all the Snapshots made by the tests in OpenSCD.
I noticed that there are old captures still in the files, because test descriptions were renamed.

How to prevent this in the future? Because it can become messy.

### PR DESCRIPTION
**Pull request by JakobVogelsang**
Close #676 

It is weird, I have not had the feeling that snapshot does have positives negatives. But this update makes me wonder. Most changes are due to now missing test which cause some leftovers. However, there are some changes in the IED editor and the SLD editor that are strange. The changes are correct so far I see, but I cannot understand why they're positive before the change. Could you have a look too? Maybe I am missing something!

Update found it: the expect(...)...equalSnapshot must be awaited. If not, then the snapshot will be created but will not be checked. Meaning if you create a new one it will be created and when you want to actively update and delete the snapshot and recreate you will see the changes, but if you do something by mistake and you are hoping the snapshots will indicate it then we need to await the snapShot.

### CODE REVIEW

**Comment by dlabordus** [comment]
Hi Jakob,

I also checked out this branch and first removed all snapshot files, but still got 2 files that are changed.

```
➜  open-scd git:(update-snapshots) ✗ find . -name "*.snap.js" -type f -delete
➜  open-scd git:(update-snapshots) ✗ npm run-script build 
.......
➜  open-scd git:(update-snapshots) ✗ git status
On branch update-snapshots
Your branch is up-to-date with 'origin/update-snapshots'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   test/integration/__snapshots__/Setting.test.snap.js
	modified:   test/integration/editors/sampledvalues/__snapshots__/SampledValues.test.snap.js

no changes added to commit (use "git add" and/or "git commit -a")
➜  open-scd git:(update-snapshots) ✗ 
```

**Comment by dlabordus** [comment]
Hi Jakob,

I also checked out this branch and first removed all snapshot files, but still got 2 files that are changed.

```
➜  open-scd git:(update-snapshots) ✗ find . -name "*.snap.js" -type f -delete
➜  open-scd git:(update-snapshots) ✗ npm run-script build 
.......
➜  open-scd git:(update-snapshots) ✗ git status
On branch update-snapshots
Your branch is up-to-date with 'origin/update-snapshots'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   test/integration/__snapshots__/Setting.test.snap.js
	modified:   test/integration/editors/sampledvalues/__snapshots__/SampledValues.test.snap.js

no changes added to commit (use "git add" and/or "git commit -a")
➜  open-scd git:(update-snapshots) ✗ 
```

**Comment by dlabordus** [comment]
Maybe for some background info in the future, if the web test runner is used await is needed.
See https://open-wc.org/docs/testing/semantic-dom-diff/

**Comment by JakobVogelsang** [comment]
Strange I have tested again and do not have any changes. Can you post the git diff outcome here. Sorry for making you so much work but that is bothering me :)

**Pull request closed without merging**
