### PR TITLE
chore(update-actions): Update Node from 14.x to 18.x

### LINKED ISSUE #918: Upgrade GitHub Actions to use newer version of NodeJS/NPM
**Is your feature request related to a problem? Please describe.**
The package-lock.json file is created using version 2, this means at least version 7 of NPM.
The build is using NodeJS 14, but if a developer is also using that version the package-lock.json will be downgraded to version 1.

**Describe the solution you'd like**
Use a newer version of NodeJS (for instance the current stable version 18 with NPM version 8) in the GitHub actions.
And also update documentation to indicate that developers should use this version.

**Requirements**
GitHub Action are using a newer version of NodeJS to build the project.

### PR DESCRIPTION
**Pull request by apupier**
- updated GitHub Actions
- provide information in readme on the version to use

fixes #918

### CODE REVIEW

**Review by ca-d — APPROVED** [review]
LGTM, thank you for the contribution and welcome to the project!

If you want some help overcoming our desperately lacking developer documentation, please feel free to [join the #open-scd channel on lfenergy.slack.com](https://join.slack.com/t/lfenergy/shared_invite/zt-f9z7c305-SYbhNb2ffXJ~8jGd_gpwWQ) and say hi! :wave:

**Comment by ca-d** [comment]
I'm sorry for pushing directly to your fork, I intended to push to my own fork and send a pull request describing an issue with an older version of some upstream development dependency and the new node version. I was surprised to find that I could simply push the change to your fork without issue.

**Review by ca-d — APPROVED** [review]
still LGTM

**Comment by apupier** [comment]
> I'm sorry for pushing directly to your fork

No problem, I always `Allow edits and access to secrets by maintainers` anyway as they are better placed than the newcomer me to know how to improve the codebase.

**Comment by danyill** [comment]
hey @apupier - around here with approval, contributors merge their own PRs (not, I think, that we told anyone that :wink:). 

I'd be keen for you to merge this when you can as it would be convenient for me too. Thanks for this PR.

**Comment by apupier** [comment]
I do not have rights to merge it:

image

**Comment by danyill** [comment]
> I do not have rights to merge it:

Oh sorry, how annoying. I'll do it.

**Pull request merged**
